/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analysis/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expense Analysis */
        get: operations["expense_analysis_api_analysis_expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/budgets/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Budget */
        put: operations["update_budget_api_analysis_budgets__month__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_config_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/transactions/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Transaction */
        post: operations["prepare_transaction_api_entries_transactions_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_entries_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/meals/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Meal */
        post: operations["prepare_meal_api_entries_meals_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Meal */
        post: operations["create_meal_api_entries_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/batch/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Batch */
        post: operations["prepare_batch_api_entries_batch_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Batch */
        post: operations["save_batch_api_entries_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meals */
        get: operations["list_meals_api_meals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diet Stats */
        get: operations["diet_stats_api_meals_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /** Update Meal */
        patch: operations["update_meal_api_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/pending-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Transactions */
        get: operations["list_pending_transactions_api_pending_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/transactions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Delete Transactions */
        post: operations["bulk_delete_transactions_api_transactions_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthenticationState */
        AuthenticationState: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** BatchDiagnostics */
        BatchDiagnostics: {
            /** Raw Count */
            raw_count: number;
            /** Block Count */
            block_count: number;
            /** Kept Count */
            kept_count: number;
            /** Rejected Records */
            rejected_records?: {
                [key: string]: unknown;
            }[];
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
        };
        /** BatchPrepareRequest */
        BatchPrepareRequest: {
            /** Text */
            text: string;
            /**
             * Default Date
             * Format: date
             */
            default_date: string;
        };
        /** BatchPrepareResponse */
        BatchPrepareResponse: {
            /** Status */
            status: string;
            /** Records */
            records: components["schemas"]["BatchRecord"][];
            diagnostics: components["schemas"]["BatchDiagnostics"];
        };
        /** BatchRecord */
        BatchRecord: {
            /**
             * Include
             * @default true
             */
            include: boolean;
            /**
             * Record Type
             * @enum {string}
             */
            record_type: "支出" | "收入" | "迁移" | "饮食";
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Time
             * @default
             */
            time: string;
            /** Description */
            description: string;
            /** Amount */
            amount?: number | null;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Subcategory
             * @default
             */
            subcategory: string;
            /** Meal Type */
            meal_type?: string | null;
            /** Foods */
            foods?: components["schemas"]["FoodInput"][];
            /** Notes */
            notes?: string | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
        };
        /** BatchSaveRequest */
        BatchSaveRequest: {
            /** Submission Id */
            submission_id: string;
            /** Records */
            records: components["schemas"]["BatchRecord"][];
        };
        /** BatchSaveResponse */
        BatchSaveResponse: {
            /** Saved Count */
            saved_count: number;
            /** Duplicate */
            duplicate: boolean;
        };
        /** BreakdownItem */
        BreakdownItem: {
            /** Category */
            category: string | null;
            /** Subcategory */
            subcategory: string | null;
            /** Total */
            total: number;
            /** Count */
            count: number;
        };
        /** BulkDeleteRequest */
        BulkDeleteRequest: {
            /** Ids */
            ids: number[];
        };
        /** BulkDeleteResponse */
        BulkDeleteResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /** CategoryConfiguration */
        CategoryConfiguration: {
            [key: string]: {
                [key: string]: string[];
            };
        };
        /** ClassificationCandidate */
        ClassificationCandidate: {
            /** Category */
            category: string;
            /** Subcategory */
            subcategory: string;
            /** Confidence */
            confidence: number;
        };
        /** CountByDate */
        CountByDate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Count */
            count: number;
        };
        /** CountByFood */
        CountByFood: {
            /** Food Name */
            food_name: string;
            /** Count */
            count: number;
        };
        /** CountByMealType */
        CountByMealType: {
            /** Meal Type */
            meal_type: string;
            /** Count */
            count: number;
        };
        /** CreateResponse */
        CreateResponse: {
            /** Id */
            id: number;
            /** Duplicate */
            duplicate: boolean;
        };
        /** DailyPoint */
        DailyPoint: {
            /** Date */
            date: string;
            /** Income */
            income: number;
            /** Expense */
            expense: number;
        };
        /** DietStatsResponse */
        DietStatsResponse: {
            /** Meal Times */
            meal_times: components["schemas"]["MealTimePoint"][];
            /** Food Freq */
            food_freq: components["schemas"]["CountByFood"][];
            /** Daily Meals */
            daily_meals: components["schemas"]["CountByDate"][];
            /** Meal Type Dist */
            meal_type_dist: components["schemas"]["CountByMealType"][];
        };
        /** ExpenseAnalysisResponse */
        ExpenseAnalysisResponse: {
            /** Months */
            months: string[];
            /** Years */
            years: string[];
            /** Selected Period */
            selected_period: string | null;
            /** Days */
            days?: number | null;
            current?: components["schemas"]["PeriodData"] | null;
            previous?: components["schemas"]["PeriodData"] | null;
            cash_current?: components["schemas"]["PeriodData"] | null;
            cash_previous?: components["schemas"]["PeriodData"] | null;
            /** Timeline */
            timeline?: components["schemas"]["PeriodSummary"][];
            /** Comparison */
            comparison?: components["schemas"]["PeriodSummary"][];
            /** Fixed Monthly Cost */
            fixed_monthly_cost?: number | null;
            budget?: components["schemas"]["MonthBudget"] | null;
            /** Cash Expense */
            cash_expense?: number | null;
            /** Amortized Expense */
            amortized_expense?: number | null;
        };
        /** FoodInput */
        FoodInput: {
            /** Food Name */
            food_name: string;
            /**
             * Quantity
             * @default
             */
            quantity: string;
            /** Ingredients */
            ingredients?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** MealCreateRequest */
        MealCreateRequest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Time */
            time: string;
            /** Meal Type */
            meal_type?: string | null;
            /** Description */
            description: string;
            /** Notes */
            notes?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Foods */
            foods: components["schemas"]["FoodInput"][];
        };
        /** MealPreparationRequest */
        MealPreparationRequest: {
            /** Description */
            description: string;
            /** Time */
            time: string;
        };
        /** MealPreparationResponse */
        MealPreparationResponse: {
            /** Status */
            status: string;
            /** Meal Type */
            meal_type?: string | null;
            /** Foods */
            foods: components["schemas"]["FoodInput"][];
            /** Confidence */
            confidence: number;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
        };
        /** MealResponse */
        MealResponse: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Time */
            time: string;
            /** Meal Type */
            meal_type?: string | null;
            /** Description */
            description: string;
            /** Notes */
            notes?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Foods */
            foods: components["schemas"]["FoodInput"][];
        };
        /** MealTimePoint */
        MealTimePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Time */
            time: string;
        };
        /** MealUpdate */
        MealUpdate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Time */
            time: string;
            /** Meal Type */
            meal_type?: string | null;
            /** Description */
            description: string;
            /** Notes */
            notes?: string | null;
            /** Foods */
            foods: components["schemas"]["FoodInput"][];
        };
        /** MonthBudget */
        MonthBudget: {
            /** Amortized Total */
            amortized_total: number | null;
            /** Cash Total */
            cash_total: number | null;
        };
        /** MonthBudgetUpdate */
        MonthBudgetUpdate: {
            /** Amortized Total */
            amortized_total?: number | null;
            /** Cash Total */
            cash_total?: number | null;
        };
        /** PeriodData */
        PeriodData: {
            /** Income */
            income: number;
            /** Expense */
            expense: number;
            /** Balance */
            balance: number;
            /** Daily */
            daily: components["schemas"]["DailyPoint"][];
            /** Expense Breakdown */
            expense_breakdown: components["schemas"]["BreakdownItem"][];
            /** Income Breakdown */
            income_breakdown: components["schemas"]["BreakdownItem"][];
        };
        /** PeriodSummary */
        PeriodSummary: {
            /** Label */
            label: string;
            /** Income */
            income: number;
            /** Expense */
            expense: number;
        };
        /** TransactionCreateRequest */
        TransactionCreateRequest: {
            /**
             * Type
             * @enum {string}
             */
            type: "支出" | "收入" | "迁移";
            /** Description */
            description: string;
            /** Amount */
            amount: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Category */
            category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Notes */
            notes?: string | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
        };
        /** TransactionPreparationRequest */
        TransactionPreparationRequest: {
            /**
             * Type
             * @enum {string}
             */
            type: "支出" | "收入" | "迁移";
            /** Description */
            description: string;
        };
        /** TransactionPreparationResponse */
        TransactionPreparationResponse: {
            /** Status */
            status: string;
            /** Category */
            category: string;
            /** Subcategory */
            subcategory: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Candidates */
            candidates?: components["schemas"]["ClassificationCandidate"][];
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Id */
            id: number;
            /**
             * Type
             * @enum {string}
             */
            type: "支出" | "收入" | "迁移";
            /** Description */
            description: string;
            /** Amount */
            amount: number;
            /** Amount Cents */
            amount_cents?: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Category */
            category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Notes */
            notes?: string | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Refund For Id */
            refund_for_id?: number | null;
            /** Amortization Months */
            amortization_months?: number | null;
            /** Amortization Start */
            amortization_start?: string | null;
            /** Subscription Id */
            subscription_id?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Type */
            type?: ("支出" | "收入" | "迁移") | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | null;
            /** Date */
            date?: string | null;
            /** Category */
            category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Notes */
            notes?: string | null;
            /** Reviewed */
            reviewed?: boolean | null;
            /** Amortization Months */
            amortization_months?: number | null;
            /** Amortization Start */
            amortization_start?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    expense_analysis_api_analysis_expenses_get: {
        parameters: {
            query?: {
                granularity?: "month" | "year";
                period?: string | null;
                basis?: "cash" | "amortized";
            };
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_budget_api_analysis_budgets__month__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: string;
            };
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthBudgetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationState"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_config_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_transaction_api_entries_transactions_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPreparationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPreparationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_entries_transactions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_meal_api_entries_meals_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPreparationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPreparationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_entries_meals_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_batch_api_entries_batch_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPrepareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPrepareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_batch_api_entries_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_api_meals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diet_stats_api_meals_stats_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_api_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_transactions_api_pending_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_transactions_api_transactions_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
