DEFAULT_CATEGORY = "其他"
DEFAULT_MEAL_TYPE = "其他"
PENDING_CATEGORY = "待分类"

TYPE_EXPENSE = "支出"
TYPE_INCOME = "收入"
TYPE_TRANSFER = "迁移"
TYPE_MEAL = "饮食"
TRANSACTION_TYPES = (TYPE_EXPENSE, TYPE_INCOME, TYPE_TRANSFER)
BATCH_RECORD_TYPES = (*TRANSACTION_TYPES, TYPE_MEAL)
TRANSACTION_TYPE_SQL_LIST = ", ".join(f"'{value}'" for value in TRANSACTION_TYPES)

STATUS_ACTIVE = "active"
STATUS_VOIDED = "voided"

REFUND_CATEGORY = "退款"

DEFAULT_CONFIDENCE_THRESHOLD = 0.75
DEFAULT_MEAL_TYPES = ("早餐", "午餐", "晚餐", "零食", DEFAULT_MEAL_TYPE)
