DEFAULT_CATEGORY = "其他"
DEFAULT_MEAL_TYPE = "其他"
PENDING_CATEGORY = "待分类"

TYPE_EXPENSE = "支出"
TYPE_INCOME = "收入"
TYPE_TRANSFER = "迁移"
TYPE_MEAL = "饮食"
TRANSACTION_TYPES = (TYPE_EXPENSE, TYPE_INCOME, TYPE_TRANSFER)
BATCH_RECORD_TYPES = (*TRANSACTION_TYPES, TYPE_MEAL)
TRANSACTION_TYPE_SQL_LIST = ", ".join(f"'{value}'" for value in TRANSACTION_TYPES)


SUBSCRIPTION_STATUS_ACTIVE = "active"

SUBSCRIPTION_CYCLE_MONTHLY = "月付"
SUBSCRIPTION_CYCLE_YEARLY = "年付"
SUBSCRIPTION_CYCLE_QUARTERLY = "季付"
SUBSCRIPTION_CYCLE_CUSTOM = "自定义"
SUBSCRIPTION_CYCLE_ONE_TIME = "一次性"

RECURRING_PAYMENT_SUBSCRIPTION = "subscription"
RECURRING_PAYMENT_PREPAID = "prepaid"

RENEWAL_MODE_SAME_DAY = "same_day"
RENEWAL_MODE_FIXED_DAYS = "fixed_days"

PLANNED_EXPENSE_STATUS_OPEN = "open"
PLANNED_EXPENSE_STATUS_COMPLETED = "completed"

REFUND_CATEGORY = "退款"

DEFAULT_CONFIDENCE_THRESHOLD = 0.75
DEFAULT_MEAL_TYPES = ("早餐", "午餐", "晚餐", "零食", DEFAULT_MEAL_TYPE)
